---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Install security updates
  apt: default_release={{ ansible_distribution_release }}-security
       update_cache={{ update_apt_cache }}
       upgrade=dist
  tags: packages
        packages.security

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - awscli
    - build-essential
    - apt-transport-https
    - ca-certificates
    - acl
    - ntp
    - htop
    - git
    - libpq-dev
    - python3.6
    - "{{ base_python_package }}-dev"
    - "{{ base_python_package }}-pip"
    - python-pycurl
    - supervisor
    - unzip
  tags: packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages
